---
- name: Abilita e avvia AppArmor
  ansible.builtin.systemd:
    name: apparmor
    enabled: true
    state: started

- name: Verifica che AppArmor sia attivo nel kernel
  ansible.builtin.command: aa-enabled
  register: apparmor_status
  changed_when: false
  failed_when: false

- name: Metti in enforce tutti i profili AppArmor disponibili
  ansible.builtin.command: aa-enforce /etc/apparmor.d/*
  changed_when: true
  failed_when: false
  when: apparmor_status.stdout is defined and apparmor_status.stdout == "Yes"
