---
- name: Distribuisci banner legale (/etc/issue.net)
  ansible.builtin.template:
    src: issue.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: "0644"

- name: Distribuisci banner legale anche su /etc/issue (console locale)
  ansible.builtin.copy:
    src: /etc/issue.net
    dest: /etc/issue
    remote_src: true
    owner: root
    group: root
    mode: "0644"

- name: Svuota il MOTD statico (sostituito dallo script dinamico sotto)
  ansible.builtin.copy:
    content: ""
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"

- name: Distribuisci lo script del MOTD dinamico post-login
  ansible.builtin.template:
    src: motd-dynamic.sh.j2
    dest: /etc/update-motd.d/10-server
    owner: root
    group: root
    mode: "0755"

- name: Rimuovi lo script MOTD di default Debian (uname)
  ansible.builtin.file:
    path: /etc/update-motd.d/10-uname
    state: absent
